### ISSUE TITLE
Deploy broken both locally and on CircleCI (w/ different versions of Meteor and Modulus CLI)

### ISSUE THREAD

**Issue by danborufka** [onmodulus/docker-run-meteor#11]
We are having an urgent problem with our deploys – they don’t go through.
Our URLs are sirenioreefbox.mod.bz and sirenio.com http://sirenio.com/ and we’re getting exit code 0 although it doesn’t seem to pass.

This is the response we are getting (when deploying to either one of them):

```
Demeteorizing application...
/mnt/home/.meteor/packages/meteor-tool/.1.3.3_1.tnlp4e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
throw error;
^
undefined
Conversion failed.
Build attempt failed, attempting again.
```

We tried deploying with different versions and on different systems – no cigar.
Last time we had troubles deploying we were advised to upgrade the Modulus CLI, so downgrading again doesn't seem like a good solution. Please advise.

**Comment by theworkflow** [comment]
Hey @danborufka. We apologize for the delayed response. This seems like a problem with the [`docker-build-meteor`](https://github.com/onmodulus/docker-build-meteor/issues/22) image. You can find your issue reported there.
