### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by jackboberg** [onmodulus/docker-run-meteor#12]
Some users are reporting issues where dependencies that are included in a root `package.json` are not available at runtime.

Reference: onmodulus/modulus-cli#141

**Comment by jackboberg** [comment]
I believe this may be resolved with onmodulus/docker-build-meteor#30

**Comment by jackboberg** [comment]
working this code thru QA now, hoping to have it available before the end of day

**Comment by jackboberg** [comment]
new build image and CLI is public, please update and try deploying again if you were having issues..

`npm i modulus@latest -g`

**Comment by talfco** [comment]
See my comment in https://github.com/onmodulus/docker-build-meteor/issues/28#issuecomment-240838743

**Comment by theworkflow** [comment]
The new updates to the build image have resolved this problem. @talfco if this is still an issue please feel free to comment and reopen.
